// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cartographer/mapping/proto/multi4submap2d.proto

#ifndef PROTOBUF_cartographer_2fmapping_2fproto_2fmulti4submap2d_2eproto__INCLUDED
#define PROTOBUF_cartographer_2fmapping_2fproto_2fmulti4submap2d_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "cartographer/mapping/proto/grid_2d.pb.h"
#include "cartographer/mapping/proto/hybrid_grid.pb.h"
#include "cartographer/transform/proto/transform.pb.h"
// @@protoc_insertion_point(includes)

namespace cartographer {
namespace mapping {
namespace proto {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_cartographer_2fmapping_2fproto_2fmulti4submap2d_2eproto();
void protobuf_AssignDesc_cartographer_2fmapping_2fproto_2fmulti4submap2d_2eproto();
void protobuf_ShutdownFile_cartographer_2fmapping_2fproto_2fmulti4submap2d_2eproto();

class Multi4Submap2D;

// ===================================================================

class Multi4Submap2D : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:cartographer.mapping.proto.Multi4Submap2D) */ {
 public:
  Multi4Submap2D();
  virtual ~Multi4Submap2D();

  Multi4Submap2D(const Multi4Submap2D& from);

  inline Multi4Submap2D& operator=(const Multi4Submap2D& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Multi4Submap2D& default_instance();

  void Swap(Multi4Submap2D* other);

  // implements Message ----------------------------------------------

  inline Multi4Submap2D* New() const { return New(NULL); }

  Multi4Submap2D* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Multi4Submap2D& from);
  void MergeFrom(const Multi4Submap2D& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Multi4Submap2D* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .cartographer.transform.proto.Rigid3d local_pose = 1;
  bool has_local_pose() const;
  void clear_local_pose();
  static const int kLocalPoseFieldNumber = 1;
  const ::cartographer::transform::proto::Rigid3d& local_pose() const;
  ::cartographer::transform::proto::Rigid3d* mutable_local_pose();
  ::cartographer::transform::proto::Rigid3d* release_local_pose();
  void set_allocated_local_pose(::cartographer::transform::proto::Rigid3d* local_pose);

  // optional int32 num_range_data = 2;
  void clear_num_range_data();
  static const int kNumRangeDataFieldNumber = 2;
  ::google::protobuf::int32 num_range_data() const;
  void set_num_range_data(::google::protobuf::int32 value);

  // optional bool finished = 3;
  void clear_finished();
  static const int kFinishedFieldNumber = 3;
  bool finished() const;
  void set_finished(bool value);

  // optional .cartographer.mapping.proto.Grid2D grid = 4;
  bool has_grid() const;
  void clear_grid();
  static const int kGridFieldNumber = 4;
  const ::cartographer::mapping::proto::Grid2D& grid() const;
  ::cartographer::mapping::proto::Grid2D* mutable_grid();
  ::cartographer::mapping::proto::Grid2D* release_grid();
  void set_allocated_grid(::cartographer::mapping::proto::Grid2D* grid);

  // @@protoc_insertion_point(class_scope:cartographer.mapping.proto.Multi4Submap2D)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::cartographer::transform::proto::Rigid3d* local_pose_;
  ::google::protobuf::int32 num_range_data_;
  bool finished_;
  ::cartographer::mapping::proto::Grid2D* grid_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_cartographer_2fmapping_2fproto_2fmulti4submap2d_2eproto();
  friend void protobuf_AssignDesc_cartographer_2fmapping_2fproto_2fmulti4submap2d_2eproto();
  friend void protobuf_ShutdownFile_cartographer_2fmapping_2fproto_2fmulti4submap2d_2eproto();

  void InitAsDefaultInstance();
  static Multi4Submap2D* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Multi4Submap2D

// optional .cartographer.transform.proto.Rigid3d local_pose = 1;
inline bool Multi4Submap2D::has_local_pose() const {
  return !_is_default_instance_ && local_pose_ != NULL;
}
inline void Multi4Submap2D::clear_local_pose() {
  if (GetArenaNoVirtual() == NULL && local_pose_ != NULL) delete local_pose_;
  local_pose_ = NULL;
}
inline const ::cartographer::transform::proto::Rigid3d& Multi4Submap2D::local_pose() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.Multi4Submap2D.local_pose)
  return local_pose_ != NULL ? *local_pose_ : *default_instance_->local_pose_;
}
inline ::cartographer::transform::proto::Rigid3d* Multi4Submap2D::mutable_local_pose() {
  
  if (local_pose_ == NULL) {
    local_pose_ = new ::cartographer::transform::proto::Rigid3d;
  }
  // @@protoc_insertion_point(field_mutable:cartographer.mapping.proto.Multi4Submap2D.local_pose)
  return local_pose_;
}
inline ::cartographer::transform::proto::Rigid3d* Multi4Submap2D::release_local_pose() {
  // @@protoc_insertion_point(field_release:cartographer.mapping.proto.Multi4Submap2D.local_pose)
  
  ::cartographer::transform::proto::Rigid3d* temp = local_pose_;
  local_pose_ = NULL;
  return temp;
}
inline void Multi4Submap2D::set_allocated_local_pose(::cartographer::transform::proto::Rigid3d* local_pose) {
  delete local_pose_;
  local_pose_ = local_pose;
  if (local_pose) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:cartographer.mapping.proto.Multi4Submap2D.local_pose)
}

// optional int32 num_range_data = 2;
inline void Multi4Submap2D::clear_num_range_data() {
  num_range_data_ = 0;
}
inline ::google::protobuf::int32 Multi4Submap2D::num_range_data() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.Multi4Submap2D.num_range_data)
  return num_range_data_;
}
inline void Multi4Submap2D::set_num_range_data(::google::protobuf::int32 value) {
  
  num_range_data_ = value;
  // @@protoc_insertion_point(field_set:cartographer.mapping.proto.Multi4Submap2D.num_range_data)
}

// optional bool finished = 3;
inline void Multi4Submap2D::clear_finished() {
  finished_ = false;
}
inline bool Multi4Submap2D::finished() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.Multi4Submap2D.finished)
  return finished_;
}
inline void Multi4Submap2D::set_finished(bool value) {
  
  finished_ = value;
  // @@protoc_insertion_point(field_set:cartographer.mapping.proto.Multi4Submap2D.finished)
}

// optional .cartographer.mapping.proto.Grid2D grid = 4;
inline bool Multi4Submap2D::has_grid() const {
  return !_is_default_instance_ && grid_ != NULL;
}
inline void Multi4Submap2D::clear_grid() {
  if (GetArenaNoVirtual() == NULL && grid_ != NULL) delete grid_;
  grid_ = NULL;
}
inline const ::cartographer::mapping::proto::Grid2D& Multi4Submap2D::grid() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.Multi4Submap2D.grid)
  return grid_ != NULL ? *grid_ : *default_instance_->grid_;
}
inline ::cartographer::mapping::proto::Grid2D* Multi4Submap2D::mutable_grid() {
  
  if (grid_ == NULL) {
    grid_ = new ::cartographer::mapping::proto::Grid2D;
  }
  // @@protoc_insertion_point(field_mutable:cartographer.mapping.proto.Multi4Submap2D.grid)
  return grid_;
}
inline ::cartographer::mapping::proto::Grid2D* Multi4Submap2D::release_grid() {
  // @@protoc_insertion_point(field_release:cartographer.mapping.proto.Multi4Submap2D.grid)
  
  ::cartographer::mapping::proto::Grid2D* temp = grid_;
  grid_ = NULL;
  return temp;
}
inline void Multi4Submap2D::set_allocated_grid(::cartographer::mapping::proto::Grid2D* grid) {
  delete grid_;
  grid_ = grid;
  if (grid) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:cartographer.mapping.proto.Multi4Submap2D.grid)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace mapping
}  // namespace cartographer

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_cartographer_2fmapping_2fproto_2fmulti4submap2d_2eproto__INCLUDED
